# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=200)),
                ('memoria', models.IntegerField(max_length=200)),
                ('disco', models.IntegerField(max_length=200)),
                ('os', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=500)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebServices.Company')),
            ],
        ),
    ]
