# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebServices', '0002_auto_20160117_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='disco',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servers',
            name='memoria',
            field=models.CharField(max_length=200),
        ),
    ]
